### ISSUE TITLE
Could not pass event BedwarsPlayerDeathMessageSendEvent

### ISSUE THREAD

**Issue by EpicJosch** [boiscljo/SBA#5]
Hi,

i have a little issue with your plugin. When im in a bedwars match and one player dies then the game ends instantly even if the bed is not destroyed. When that happens i get this error in the console

`[19:58:36 ERROR]: Could not pass event BedwarsPlayerDeathMessageSendEvent to SBA v1.5.7.2-h8
java.lang.IllegalArgumentException: Illegal ending tag </gray> (position 166): No tag is opened
        at sba.sl.minitag.MiniTagParser.parse(MiniTagParser.java:127) ~[?:?]
        at sba.sl.spectator.mini.MiniMessageParser.parse(MiniMessageParser.java:64) ~[?:?]
        at sba.sl.spectator.Component.fromMiniMessage(Component.java:79) ~[?:?]
        at io.github.pronze.sba.lang.Message.toMiniMessage(Message.java:86) ~[?:?]
        at io.github.pronze.sba.lang.Message.toString(Message.java:184) ~[?:?]
        at io.github.pronze.sba.listener.BedwarsCustomMessageModifierListener.onBedWarsPlayerDeathEvent(BedwarsCustomMessageModifierListener.java:107) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor764.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.screamingsandals.bedwars.listener.PlayerListener.onPlayerDeath(PlayerListener.java:115) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor626.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:876) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:818) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityLiving.an(EntityLiving.java:2110) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.Entity.doVoidDamage(Entity.java:697) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.Entity.performVoidDamage(Entity.java:692) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:593) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:360) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:530) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

i dont really know if the game ends because of that issue but i wanna get this fixed anyways..

Can you please help me here?

**Comment by boiscljo** [comment]
> Hi,
> 
> 
> 
> i have a little issue with your plugin. When im in a bedwars match and one player dies then the game ends instantly even if the bed is not destroyed. When that happens i get this error in the console
> 
> 
> 
> `[19:58:36 ERROR]: Could not pass event BedwarsPlayerDeathMessageSendEvent to SBA v1.5.7.2-h8
> 
> java.lang.IllegalArgumentException: Illegal ending tag </gray> (position 166): No tag is opened
> 
>         at sba.sl.minitag.MiniTagParser.parse(MiniTagParser.java:127) ~[?:?]
> 
>         at sba.sl.spectator.mini.MiniMessageParser.parse(MiniMessageParser.java:64) ~[?:?]
> 
>         at sba.sl.spectator.Component.fromMiniMessage(Component.java:79) ~[?:?]
> 
>         at io.github.pronze.sba.lang.Message.toMiniMessage(Message.java:86) ~[?:?]
> 
>         at io.github.pronze.sba.lang.Message.toString(Message.java:184) ~[?:?]
> 
>         at io.github.pronze.sba.listener.BedwarsCustomMessageModifierListener.onBedWarsPlayerDeathEvent(BedwarsCustomMessageModifierListener.java:107) ~[?:?]
> 
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor764.execute(Unknown Source) ~[?:?]
> 
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.screamingsandals.bedwars.listener.PlayerListener.onPlayerDeath(PlayerListener.java:115) ~[?:?]
> 
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor626.execute(Unknown Source) ~[?:?]
> 
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:876) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:818) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityLiving.an(EntityLiving.java:2110) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.Entity.doVoidDamage(Entity.java:697) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.Entity.performVoidDamage(Entity.java:692) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:593) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:360) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:530) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
> 
>         at java.lang.Thread.run(Thread.java:831) [?:?]`
> 
> 
> 
> i dont really know if the game ends because of that issue but i wanna get this fixed anyways..
> 
> 
> 
> Can you please help me here?

The issue is with your translation file that contains a </gray> without a <gray> before, since end tags are optionnal you can simply remove the </gray> from the config

**Comment by boiscljo** [comment]
The default config file has been updated to remove all </gray> to fix the issue. A manual change to the existing translation is required to fix existing installations.
