### ISSUE TITLE
Server Lag and Console Errors After Placing "Diamond" Refresh Point

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [boiscljo/SBA#70]
Hey, after I placed a "diamond" refresh point, the server started lagging, and errors appeared in the console!

Version: 1.12.2
SBA and Bedwars versions: both are the latest versions

Log:
`[03:48:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[03:48:04 ERROR]: An exception occurred serializing packet of class: ClientboundSetEntityDataPacket
[03:48:04 WARN]: java.lang.UnsupportedOperationException: Can't unwrap object to java.lang.Integer
[03:48:04 WARN]:        at sba.sl.u.BasicNullableWrapper.as(BasicNullableWrapper.java:57)
[03:48:04 WARN]:        at sba.sl.impl.bukkit.BukkitServer.getProtocolVersion0(BukkitServer.java:606)
[03:48:04 WARN]:        at sba.sl.Server.getProtocolVersion(Server.java:124)
[03:48:04 WARN]:        at sba.sl.p.PacketWriter.protocol(PacketWriter.java:591)
[03:48:04 WARN]:        at sba.sl.p.MetadataItem$ByteMetadataItem.write(MetadataItem.java:214)
[03:48:04 WARN]:        at sba.sl.p.PacketWriter.writeDataWatcherCollection(PacketWriter.java:566)
[03:48:04 WARN]:        at sba.sl.p.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:39)
[03:48:04 WARN]:        at sba.sl.impl.bukkit.packet.BukkitPacketMapper.sendPacket0(BukkitPacketMapper.java:58)
[03:48:04 WARN]:        at sba.sl.p.PacketMapper.sendPacket(PacketMapper.java:62)
[03:48:04 WARN]:        at sba.sl.p.AbstractPacket.sendPacket(AbstractPacket.java:45)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$update$3(HologramImpl.java:244)
[03:48:04 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.update(HologramImpl.java:244)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$startRotationTask$18(HologramImpl.java:435)
[03:48:04 WARN]:        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$startRotationTask$19(HologramImpl.java:435)
[03:48:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[03:48:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[03:48:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:48:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:48:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:48:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[03:48:04 ERROR]: An exception occurred serializing packet of class: ClientboundSetEntityDataPacket
[03:48:04 WARN]: java.lang.UnsupportedOperationException: Can't unwrap object to java.lang.Integer
[03:48:04 WARN]:        at sba.sl.u.BasicNullableWrapper.as(BasicNullableWrapper.java:57)
[03:48:04 WARN]:        at sba.sl.impl.bukkit.BukkitServer.getProtocolVersion0(BukkitServer.java:606)
[03:48:04 WARN]:        at sba.sl.Server.getProtocolVersion(Server.java:124)
[03:48:04 WARN]:        at sba.sl.p.PacketWriter.protocol(PacketWriter.java:591)
[03:48:04 WARN]:        at sba.sl.p.MetadataItem$ByteMetadataItem.write(MetadataItem.java:214)
[03:48:04 WARN]:        at sba.sl.p.PacketWriter.writeDataWatcherCollection(PacketWriter.java:566)
[03:48:04 WARN]:        at sba.sl.p.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:39)
[03:48:04 WARN]:        at sba.sl.impl.bukkit.packet.BukkitPacketMapper.sendPacket0(BukkitPacketMapper.java:58)
[03:48:04 WARN]:        at sba.sl.p.PacketMapper.sendPacket(PacketMapper.java:62)
[03:48:04 WARN]:        at sba.sl.p.AbstractPacket.sendPacket(AbstractPacket.java:45)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$update$3(HologramImpl.java:244)
[03:48:04 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.update(HologramImpl.java:244)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$startRotationTask$18(HologramImpl.java:435)
[03:48:04 WARN]:        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[03:48:04 WARN]:        at sba.sl.h.HologramImpl.lambda$startRotationTask$19(HologramImpl.java:435)
[03:48:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[03:48:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[03:48:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:48:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:48:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:48:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by Misat11** [comment]
[SBA-1.5.13.1-all.zip](https://github.com/user-attachments/files/16270573/SBA-1.5.13.1-all.zip)
Can you try this build of SBA? It should fix your problem.

**Comment by BluDood** [comment]
> [SBA-1.5.13.1-all.zip](https://github.com/user-attachments/files/16270573/SBA-1.5.13.1-all.zip) Can you try this build of SBA? It should fix your problem.

I had the same problem (Paper 1.8.8), and this fixed it for me! Thanks!

**Comment by boiscljo** [comment]
Fixed in 1.5.13.2
