### ISSUE TITLE
Lobby scoreboard error when coutdown

### ISSUE THREAD

**Issue by Chaostarts** [boiscljo/SBA#72]
[20:13:02 WARN]: [SBA] Task #1182 for SBA v1.5.13.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
        at io.github.pronze.sba.visuals.LobbyScoreboardManager.lambda$process$10(LobbyScoreboardManager.java:193) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at io.github.pronze.sba.visuals.LobbyScoreboardManager.process(LobbyScoreboardManager.java:188) ~[?:?]
        at io.github.pronze.sba.visuals.LobbyScoreboardManager.lambda$createBoard$1(LobbyScoreboardManager.java:80) ~[?:?]
        at io.github.pronze.lib.pronzelib.scoreboards.Scoreboard$1.run(Scoreboard.java:216) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-2
1fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.Team$Option
        ... 12 more

**Comment by Misat11** [comment]
This error should be now fixed in 1.5.13.3
