### ISSUE TITLE
Error in Lobby

### ISSUE THREAD

**Issue by yeying-xingchen** [boiscljo/SBA#91]
ERROR LOG:
```[19:50:33 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 59
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:50:33 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 59
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:28:04 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:28:04 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:28:04 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:28:04 WARN]: [SBA] Plugin SBA v1.5.13.6 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:497) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:551) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:242) ~[guava-33.3.1-jre.jar:?]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:224) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.createTeams(ScoreboardDriverV1.java:155) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.drivers.v1.ScoreboardDriverV1.setLineCount(ScoreboardDriverV1.java:123) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.implementations.WrapperBoard.setLineCount(WrapperBoard.java:47) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.lib.pronzelib.scoreboards.scoreboardr.board.ConfigBoard.run(ConfigBoard.java:116) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[20:28:04 ERROR]: Could not pass event PlayerQuitEvent to SBA v1.5.13.6
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:638) ~[fastutil-8.5.15.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1146) ~[fastutil-8.5.15.jar:?]
        at org.bukkit.craftbukkit.scoreboard.CraftScoreboardManager.setPlayerBoard(CraftScoreboardManager.java:101) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.craftbukkit.entity.CraftPlayer.setScoreboard(CraftPlayer.java:2785) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.sba.visuals.MainLobbyVisualsManager.remove(MainLobbyVisualsManager.java:250) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at 【玩法】SBA-1.5.13.6-all.jar/io.github.pronze.sba.visuals.MainLobbyVisualsManager.onPlayerLeave(MainLobbyVisualsManager.java:171) ~[【玩法】SBA-1.5.13.6-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:554) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:539) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2190) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2170) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2157) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:910) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:268) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.MinecraftServer.tickConnection(MinecraftServer.java:1919) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.dedicated.DedicatedServer.tickConnection(DedicatedServer.java:453) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1892) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1666) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-12-c17ef64]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by yeying-xingchen** [comment]
@boiscljo Please fix it.
in paper Test Build 14

**Comment by boiscljo** [comment]
I do not support test build, I'll test once a stable build is released
